// Code generated by "stringer -type=token -linecomment -output=token_string.go"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[xNone-0]
	_ = x[xNumber-1]
	_ = x[xText-2]
	_ = x[xIdent-3]
	_ = x[xTrue-4]
	_ = x[xFalse-5]
	_ = x[xSubroutine-6]
	_ = x[xDim-7]
	_ = x[xLet-8]
	_ = x[xInput-9]
	_ = x[xPrint-10]
	_ = x[xIf-11]
	_ = x[xThen-12]
	_ = x[xElseIf-13]
	_ = x[xElse-14]
	_ = x[xWhile-15]
	_ = x[xFor-16]
	_ = x[xTo-17]
	_ = x[xStep-18]
	_ = x[xCall-19]
	_ = x[xEnd-20]
	_ = x[xAdd-21]
	_ = x[xSub-22]
	_ = x[xAmp-23]
	_ = x[xMul-24]
	_ = x[xDiv-25]
	_ = x[xMod-26]
	_ = x[xPow-27]
	_ = x[xEq-28]
	_ = x[xNe-29]
	_ = x[xGt-30]
	_ = x[xGe-31]
	_ = x[xLt-32]
	_ = x[xLe-33]
	_ = x[xAnd-34]
	_ = x[xOr-35]
	_ = x[xNot-36]
	_ = x[xNewLine-37]
	_ = x[xLeftPar-38]
	_ = x[xRightPar-39]
	_ = x[xLeftBr-40]
	_ = x[xRightBr-41]
	_ = x[xComma-42]
	_ = x[xEof-43]
}

const _token_name = "xNoneթիվտեքստիդենտիֆիկատորTRUEFALSESUBDIMLETINPUTPRINTIFTHENELSEIFELSEWHILEFORTOSTEPCALLEND+-&*/\\^=<>>>=<<=ANDORNOT<-/()[],ֆայլի վերջը"

var _token_index = [...]uint8{0, 5, 11, 21, 47, 51, 56, 59, 62, 65, 70, 75, 77, 81, 87, 91, 96, 99, 101, 105, 109, 112, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123, 125, 126, 128, 131, 133, 136, 139, 140, 141, 142, 143, 144, 165}

func (i token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_token_index)-1 {
		return "token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _token_name[_token_index[idx]:_token_index[idx+1]]
}
